name: Merge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  merge:
    env:
      BRANCH: main
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/merge-upstream@v1
        with:
          branch: ${{ env.BRANCH }}
          upstream-branch: ${{ env.BRANCH }}
          upstream: libinjection/libinjection
